name: dropzone_angular_dart
description: DropzoneJS for Angular Dart
version: 0.2.0
author: Nick Ng <ngyewch@gmail.com>
homepage: https://github.com/ngyewch/dropzone-angular-dart

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  browser: '>=0.10.0 <0.11.0'

#transformers:
#- angular:
#    platform_directives:
#    - 'package:angular/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular/common.dart#COMMON_PIPES'
#    entry_points: web/main.dart

